### ISSUE TITLE
STOP POSTING ABOUT AMONG US

### ISSUE THREAD

**Issue by CallumPringle** [ryanmw05/2D-game#3]
im tired of seeing it, my friends on tiktok send me memes, on discord its all memes, i was on a server, and all the channels were just among us, i looked at a trash can and said "thats a bit sussy", i looked at my penis and thought about the astronauts helmet and said "penis more like, PEEN-SUS AAAHHHHH"

**Comment by LewisZ497** [comment]
# @CallumPringle ur sus
